# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/stephanie/W&M/Fall 2015/CSCI 420/SumoSlammers/Sumo-Slammers"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/stephanie/W&M/Fall 2015/CSCI 420/SumoSlammers/Sumo-Slammers"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/stephanie/W&M/Fall 2015/CSCI 420/SumoSlammers/Sumo-Slammers/CMakeFiles" "/home/stephanie/W&M/Fall 2015/CSCI 420/SumoSlammers/Sumo-Slammers/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/stephanie/W&M/Fall 2015/CSCI 420/SumoSlammers/Sumo-Slammers/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sumo_slammers

# Build rule for target.
sumo_slammers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sumo_slammers
.PHONY : sumo_slammers

# fast build rule for target.
sumo_slammers/fast:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/build
.PHONY : sumo_slammers/fast

bin/sumo_slammers.o: bin/sumo_slammers.cpp.o
.PHONY : bin/sumo_slammers.o

# target to build an object file
bin/sumo_slammers.cpp.o:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/bin/sumo_slammers.cpp.o
.PHONY : bin/sumo_slammers.cpp.o

bin/sumo_slammers.i: bin/sumo_slammers.cpp.i
.PHONY : bin/sumo_slammers.i

# target to preprocess a source file
bin/sumo_slammers.cpp.i:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/bin/sumo_slammers.cpp.i
.PHONY : bin/sumo_slammers.cpp.i

bin/sumo_slammers.s: bin/sumo_slammers.cpp.s
.PHONY : bin/sumo_slammers.s

# target to generate assembly for a file
bin/sumo_slammers.cpp.s:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/bin/sumo_slammers.cpp.s
.PHONY : bin/sumo_slammers.cpp.s

src/Collidable.o: src/Collidable.cpp.o
.PHONY : src/Collidable.o

# target to build an object file
src/Collidable.cpp.o:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/Collidable.cpp.o
.PHONY : src/Collidable.cpp.o

src/Collidable.i: src/Collidable.cpp.i
.PHONY : src/Collidable.i

# target to preprocess a source file
src/Collidable.cpp.i:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/Collidable.cpp.i
.PHONY : src/Collidable.cpp.i

src/Collidable.s: src/Collidable.cpp.s
.PHONY : src/Collidable.s

# target to generate assembly for a file
src/Collidable.cpp.s:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/Collidable.cpp.s
.PHONY : src/Collidable.cpp.s

src/LocationalMap.o: src/LocationalMap.cpp.o
.PHONY : src/LocationalMap.o

# target to build an object file
src/LocationalMap.cpp.o:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/LocationalMap.cpp.o
.PHONY : src/LocationalMap.cpp.o

src/LocationalMap.i: src/LocationalMap.cpp.i
.PHONY : src/LocationalMap.i

# target to preprocess a source file
src/LocationalMap.cpp.i:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/LocationalMap.cpp.i
.PHONY : src/LocationalMap.cpp.i

src/LocationalMap.s: src/LocationalMap.cpp.s
.PHONY : src/LocationalMap.s

# target to generate assembly for a file
src/LocationalMap.cpp.s:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/LocationalMap.cpp.s
.PHONY : src/LocationalMap.cpp.s

src/Logic.o: src/Logic.cpp.o
.PHONY : src/Logic.o

# target to build an object file
src/Logic.cpp.o:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/Logic.cpp.o
.PHONY : src/Logic.cpp.o

src/Logic.i: src/Logic.cpp.i
.PHONY : src/Logic.i

# target to preprocess a source file
src/Logic.cpp.i:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/Logic.cpp.i
.PHONY : src/Logic.cpp.i

src/Logic.s: src/Logic.cpp.s
.PHONY : src/Logic.s

# target to generate assembly for a file
src/Logic.cpp.s:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/Logic.cpp.s
.PHONY : src/Logic.cpp.s

src/MainMenu.o: src/MainMenu.cpp.o
.PHONY : src/MainMenu.o

# target to build an object file
src/MainMenu.cpp.o:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/MainMenu.cpp.o
.PHONY : src/MainMenu.cpp.o

src/MainMenu.i: src/MainMenu.cpp.i
.PHONY : src/MainMenu.i

# target to preprocess a source file
src/MainMenu.cpp.i:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/MainMenu.cpp.i
.PHONY : src/MainMenu.cpp.i

src/MainMenu.s: src/MainMenu.cpp.s
.PHONY : src/MainMenu.s

# target to generate assembly for a file
src/MainMenu.cpp.s:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/MainMenu.cpp.s
.PHONY : src/MainMenu.cpp.s

src/PlayerView.o: src/PlayerView.cpp.o
.PHONY : src/PlayerView.o

# target to build an object file
src/PlayerView.cpp.o:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/PlayerView.cpp.o
.PHONY : src/PlayerView.cpp.o

src/PlayerView.i: src/PlayerView.cpp.i
.PHONY : src/PlayerView.i

# target to preprocess a source file
src/PlayerView.cpp.i:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/PlayerView.cpp.i
.PHONY : src/PlayerView.cpp.i

src/PlayerView.s: src/PlayerView.cpp.s
.PHONY : src/PlayerView.s

# target to generate assembly for a file
src/PlayerView.cpp.s:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/PlayerView.cpp.s
.PHONY : src/PlayerView.cpp.s

src/Profile.o: src/Profile.cpp.o
.PHONY : src/Profile.o

# target to build an object file
src/Profile.cpp.o:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/Profile.cpp.o
.PHONY : src/Profile.cpp.o

src/Profile.i: src/Profile.cpp.i
.PHONY : src/Profile.i

# target to preprocess a source file
src/Profile.cpp.i:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/Profile.cpp.i
.PHONY : src/Profile.cpp.i

src/Profile.s: src/Profile.cpp.s
.PHONY : src/Profile.s

# target to generate assembly for a file
src/Profile.cpp.s:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/Profile.cpp.s
.PHONY : src/Profile.cpp.s

src/Terrain.o: src/Terrain.cpp.o
.PHONY : src/Terrain.o

# target to build an object file
src/Terrain.cpp.o:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/Terrain.cpp.o
.PHONY : src/Terrain.cpp.o

src/Terrain.i: src/Terrain.cpp.i
.PHONY : src/Terrain.i

# target to preprocess a source file
src/Terrain.cpp.i:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/Terrain.cpp.i
.PHONY : src/Terrain.cpp.i

src/Terrain.s: src/Terrain.cpp.s
.PHONY : src/Terrain.s

# target to generate assembly for a file
src/Terrain.cpp.s:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/Terrain.cpp.s
.PHONY : src/Terrain.cpp.s

src/TerrainView.o: src/TerrainView.cpp.o
.PHONY : src/TerrainView.o

# target to build an object file
src/TerrainView.cpp.o:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/TerrainView.cpp.o
.PHONY : src/TerrainView.cpp.o

src/TerrainView.i: src/TerrainView.cpp.i
.PHONY : src/TerrainView.i

# target to preprocess a source file
src/TerrainView.cpp.i:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/TerrainView.cpp.i
.PHONY : src/TerrainView.cpp.i

src/TerrainView.s: src/TerrainView.cpp.s
.PHONY : src/TerrainView.s

# target to generate assembly for a file
src/TerrainView.cpp.s:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/TerrainView.cpp.s
.PHONY : src/TerrainView.cpp.s

src/Wrestler.o: src/Wrestler.cpp.o
.PHONY : src/Wrestler.o

# target to build an object file
src/Wrestler.cpp.o:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/Wrestler.cpp.o
.PHONY : src/Wrestler.cpp.o

src/Wrestler.i: src/Wrestler.cpp.i
.PHONY : src/Wrestler.i

# target to preprocess a source file
src/Wrestler.cpp.i:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/Wrestler.cpp.i
.PHONY : src/Wrestler.cpp.i

src/Wrestler.s: src/Wrestler.cpp.s
.PHONY : src/Wrestler.s

# target to generate assembly for a file
src/Wrestler.cpp.s:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/Wrestler.cpp.s
.PHONY : src/Wrestler.cpp.s

src/tinyxml2.o: src/tinyxml2.cpp.o
.PHONY : src/tinyxml2.o

# target to build an object file
src/tinyxml2.cpp.o:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/tinyxml2.cpp.o
.PHONY : src/tinyxml2.cpp.o

src/tinyxml2.i: src/tinyxml2.cpp.i
.PHONY : src/tinyxml2.i

# target to preprocess a source file
src/tinyxml2.cpp.i:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/tinyxml2.cpp.i
.PHONY : src/tinyxml2.cpp.i

src/tinyxml2.s: src/tinyxml2.cpp.s
.PHONY : src/tinyxml2.s

# target to generate assembly for a file
src/tinyxml2.cpp.s:
	$(MAKE) -f CMakeFiles/sumo_slammers.dir/build.make CMakeFiles/sumo_slammers.dir/src/tinyxml2.cpp.s
.PHONY : src/tinyxml2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sumo_slammers"
	@echo "... bin/sumo_slammers.o"
	@echo "... bin/sumo_slammers.i"
	@echo "... bin/sumo_slammers.s"
	@echo "... src/Collidable.o"
	@echo "... src/Collidable.i"
	@echo "... src/Collidable.s"
	@echo "... src/LocationalMap.o"
	@echo "... src/LocationalMap.i"
	@echo "... src/LocationalMap.s"
	@echo "... src/Logic.o"
	@echo "... src/Logic.i"
	@echo "... src/Logic.s"
	@echo "... src/MainMenu.o"
	@echo "... src/MainMenu.i"
	@echo "... src/MainMenu.s"
	@echo "... src/PlayerView.o"
	@echo "... src/PlayerView.i"
	@echo "... src/PlayerView.s"
	@echo "... src/Profile.o"
	@echo "... src/Profile.i"
	@echo "... src/Profile.s"
	@echo "... src/Terrain.o"
	@echo "... src/Terrain.i"
	@echo "... src/Terrain.s"
	@echo "... src/TerrainView.o"
	@echo "... src/TerrainView.i"
	@echo "... src/TerrainView.s"
	@echo "... src/Wrestler.o"
	@echo "... src/Wrestler.i"
	@echo "... src/Wrestler.s"
	@echo "... src/tinyxml2.o"
	@echo "... src/tinyxml2.i"
	@echo "... src/tinyxml2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

